### ISSUE TITLE
Gesell UX Field Test Ready

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#140]
Epic encompasses everything needed for the pre-launch at SCS. Network will be Gesell

* [x] reset Gesell with 0.8.0 node
* [x] publish updated app
* [x] publish updated explorer
